# Generated by Django 5.0.4 on 2024-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_description', models.CharField(max_length=64)),
                ('relevent_section', models.CharField(max_length=64)),
                ('project_owner', models.CharField(max_length=512)),
                ('submitted_by', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
