# Generated by Django 5.0.4 on 2024-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0002_alter_bug_automation_team_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='automation_team_remark',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
