# Generated by Django 5.0.4 on 2024-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0003_alter_bug_automation_team_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='issue_closer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
