# Generated by Django 5.0.4 on 2024-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0006_alter_bug_automation_team_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='automation_team_update',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
